name: Elements
main: com.ihusker.elements.Elements
version: 0.0.2
api-version: "1.16"
author: iHusker
authors: [iHusker]

commands:
  delwarp:
    description: Remove an existing warp.
  setwarp:
    description: Set a new or existing warp.
  warp:
    description: Warp to a target location.
  warps:
    description: Displayes a lit of warps.
